### ISSUE TITLE
Installation problem: package requires wheel to be installed correct

### ISSUE THREAD

**Issue by cstapler** [tstapler/cfgcaddy#1]
On a fresh Linux Mint installation, I received an error when running `pip install cfgcaddy`. The following screen-shots are of the error messages.

![screenshot from 2017-10-31 13-21-46](https://user-images.githubusercontent.com/11775199/32241682-cc1aca5e-be3e-11e7-89bd-00a63bae5230.jpg)

![screenshot from 2017-10-31 13-00-00](https://user-images.githubusercontent.com/11775199/32241518-5e2b65e4-be3e-11e7-9477-17ce2de8acd6.jpg)

I was able to get pass this and properly download cfgcaddy by running `pip install wheel`. Not sure if this is something you can fix on your end.

 Let me know if you need any more details!

**Comment by tstapler** [comment]
I've been looking into simplifying cfgcaddy's dependencies. I think that should help.
